scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: front_180_filter
      type: laser_filters/LaserScanAngularBoundsFilterInPlace
      params:
        lower_angle: 2.40855  # 90° - left side
        upper_angle: 3.87463 # 270° - right side (front semicircle)
