scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: front_180_filter
      type: laser_filters/LaserScanAngularBoundsFilterInPlace
      params:
        lower_angle: 2.40855  
        upper_angle: 3.87463 
